export const LOGIN = "LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const STOP_LOGIN_LOADING = "STOP_LOGIN_LOADING";
export const SHOW_FIELD_ERRORS = "SHOW_FIELD_ERRORS";
export const HIDE_FIELD_ERRORS = "HIDE_FIELD_ERRORS";

export const APP_STATE_UPDATE = "APP_STATE_UPDATE";

export const SET_WELCOME_MODAL = "SET_WELCOME_MODAL";

export const LOGOUT = "LOGOUT";
export const RESET_STATE = "RESET_STATE";

export const SELECT_BANK = "SELECT_BANK";
export const CHANGE_SETUP_INPUT = "CHANGE_SETUP_INPUT";

export const SET_LINKED_ALIASES = "SET_LINKED_ALIASES";
export const VALIDATING_PHONE_NUMBER = "VALIDATING_PHONE_NUMBER";
export const VALIDATED_PHONE_NUMBER = "VALIDATED_PHONE_NUMBER";
export const VALIDATED_OPTIONS_PHONE_NUMBER = "VALIDATED_OPTIONS_PHONE_NUMBER";
export const SET_PAGE_LOADING = "SET_PAGE_LOADING";
export const SET_USER_EXIST = "SET_USER_EXIST";
export const SET_ACTION_LOADING = "SET_ACTION_LOADING";
export const SET_UERID = "SET_UERID";

export const SET_TRANSFER_SUCCESSFUL = "SET_TRANSFER_SUCCESSFUL";
export const SET_LINK_SUCCESSFUL = "SET_LINK_SUCCESSFUL";
export const SET_UNLINK_SUCCESSFUL = "SET_UNLINK_SUCCESSFUL";
export const RESET_OTP_FIELDS = "RESET_OTP_FIELDS";

export const SET_MAX_TRANSFER_AMOUNT = "SET_MAX_TRANSFER_AMOUNT";
export const SET_REVERSAL_DURATION = "SET_REVERSAL_DURATION";

export const SET_ALL_CONTACTS = "SET_ALL_CONTACTS";

export const SET_SPLASH_SCREEN = "SET_SPLASH_SCREEN";
