import { IBank } from '../Interfaces';
import { kwiklliSuperAdminAuthCredentials } from './authCredentials';


export const registeredBanks: Array<IBank> = [
  {
    appName: "Select a bank",
    appIcon: "https://res.cloudinary.com/shaolinmkz/image/upload/v1605358954/softcom/kwiklli/npay-logo.svg",
    apiKey: "<BANK_API_KEY>",
    bankCode: "<BANK_CODE>",
    label: "Select a bank",
    value: "<BANK_CODE>",
    username: "",
    password: "",
  },
  {
    appName: "Zenith Bank",
    appIcon: "https://res.cloudinary.com/shaolinmkz/image/upload/v1628589246/Random-Icons/banks_logo/Zenith_Bank.png",
    apiKey: "<BANK_API_KEY>",
    bankCode: "<BANK_CODE>",
    label: "Zenith Bank",
    value: "<BANK_CODE>",
    ...kwiklliSuperAdminAuthCredentials,
  },
  {
    appName: "Access Bank",
    appIcon: "https://res.cloudinary.com/shaolinmkz/image/upload/v1626638585/Random-Icons/access-bank.png",
    apiKey: "<BANK_API_KEY>",
    bankCode: "<BANK_CODE>",
    label: "Access Bank",
    value: "<BANK_CODE>",
    ...kwiklliSuperAdminAuthCredentials,
  },
  {
    appName: "Guaranty Trust Bank",
    appIcon: "https://res.cloudinary.com/shaolinmkz/image/upload/v1628588993/Random-Icons/banks_logo/Guaranty_Trust_Bank.png",
    apiKey: "<BANK_API_KEY>",
    bankCode: "<BANK_CODE>",
    label: "Guaranty Trust Bank",
    value: "<BANK_CODE>",
    ...kwiklliSuperAdminAuthCredentials,
  },
  {
    appName: "Sterling Bank",
    appIcon: "https://res.cloudinary.com/shaolinmkz/image/upload/v1628589166/Random-Icons/banks_logo/Sterling_Bank_Plc.png",
    apiKey: "<BANK_API_KEY>",
    bankCode: "<BANK_CODE>",
    label: "Sterling Bank",
    value: "<BANK_CODE>",
    ...kwiklliSuperAdminAuthCredentials,
  },
  {
    appName: "Union Bank",
    appIcon: "https://res.cloudinary.com/shaolinmkz/image/upload/v1628589196/Random-Icons/banks_logo/Union_Bank.png",
    apiKey: "<BANK_API_KEY>",
    bankCode: "<BANK_CODE>",
    label: "Union Bank",
    value: "<BANK_CODE>",
    ...kwiklliSuperAdminAuthCredentials,
  },
  {
    appName: "Keystone Bank",
    appIcon: "https://res.cloudinary.com/shaolinmkz/image/upload/v1628589037/Random-Icons/banks_logo/Keystone_Bank.png",
    apiKey: "<BANK_API_KEY>",
    bankCode: "<BANK_CODE>",
    label: "Keystone Bank",
    value: "<BANK_CODE>",
    ...kwiklliSuperAdminAuthCredentials,
  },
  {
    appName: "First Bank",
    appIcon: "https://res.cloudinary.com/shaolinmkz/image/upload/v1628588967/Random-Icons/banks_logo/First_Bank.png",
    apiKey: "<BANK_API_KEY>",
    bankCode: "<BANK_CODE>",
    label: "First Bank",
    value: "<BANK_CODE>",
    ...kwiklliSuperAdminAuthCredentials,
  },
  {
    appName: "Heritage Bank",
    appIcon: "https://res.cloudinary.com/shaolinmkz/image/upload/v1628589005/Random-Icons/banks_logo/Heritage_Bank_PLC.png",
    apiKey: "<BANK_API_KEY>",
    bankCode: "<BANK_CODE>",
    label: "Heritage Bank",
    value: "<BANK_CODE>",
    ...kwiklliSuperAdminAuthCredentials,
  },
];
